// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameConfig = "config"

// Config mapped from table <config>
type Config struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ConfigKey   string    `gorm:"column:config_key;not null;comment:配置键" json:"config_key"`                   // 配置键
	ConfigValue string    `gorm:"column:config_value;not null;comment:配置值" json:"config_value"`               // 配置值
	ConfigType  string    `gorm:"column:config_type;not null;comment:配置值类型" json:"config_type"`               // 配置值类型
	Description string    `gorm:"column:description;comment:配置描述" json:"description"`                         // 配置描述
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}
