// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameLdCategory = "ld_category"

// LdCategory 博客-分类表
type LdCategory struct {
	ID               int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CategoryName     string `gorm:"column:category_name;comment:分类名称" json:"category_name"`                            // 分类名称
	CategoryCover    string `gorm:"column:category_cover;comment:分类封面" json:"category_cover"`                          // 分类封面
	CategoryURL      string `gorm:"column:category_url;comment:分类路径" json:"category_url"`                              // 分类路径
	CategoryDescribe string `gorm:"column:category_describe;comment:描述" json:"category_describe"`                      // 描述
	CategoryColor    string `gorm:"column:category_color;default:_utf8mb4\'#000\';comment:标签颜色" json:"category_color"` // 标签颜色
}

// TableName LdCategory's table name
func (*LdCategory) TableName() string {
	return TableNameLdCategory
}
