// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameLdMenu = "ld_menu"

// LdMenu 博客-菜单表
type LdMenu struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentMenuID int64  `gorm:"column:parent_menu_id;comment:上一级菜单id" json:"parent_menu_id"`  // 上一级菜单id
	MenuIcon     string `gorm:"column:menu_icon;comment:菜单图标" json:"menu_icon"`               // 菜单图标
	MenuName     string `gorm:"column:menu_name;comment:菜单名称" json:"menu_name"`               // 菜单名称
	MenuSort     int32  `gorm:"column:menu_sort;comment:排序" json:"menu_sort"`                 // 排序
	MenuTarget   string `gorm:"column:menu_target;comment:打开方式 新标签or当前标签" json:"menu_target"` // 打开方式 新标签or当前标签
	MenuURL      string `gorm:"column:menu_url;comment:菜单路径" json:"menu_url"`                 // 菜单路径
}

// TableName LdMenu's table name
func (*LdMenu) TableName() string {
	return TableNameLdMenu
}
