// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameLdNote = "ld_notes"

// LdNote 博客-文章表
type LdNote struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title         string    `gorm:"column:title;comment:文章标题" json:"title"`                                       // 文章标题
	CoverImage    string    `gorm:"column:cover_image;comment:文章封面图片" json:"cover_image"`                         // 文章封面图片
	ContentMd     string    `gorm:"column:content_md;comment:markdown版的文章内容" json:"content_md"`                   // markdown版的文章内容
	Top           bool      `gorm:"column:top;comment:是否置顶" json:"top"`                                           // 是否置顶
	TypeID        int64     `gorm:"column:type_id;comment:类型" json:"type_id"`                                     // 类型
	TagIds        int64     `gorm:"column:tag_ids;comment:标签" json:"tag_ids"`                                     // 标签
	NotesStatus   bool      `gorm:"column:notes_status;comment:状态" json:"notes_status"`                           // 状态
	IsRecommended bool      `gorm:"column:is_recommended;default:1;comment:是否推荐" json:"is_recommended"`           // 是否推荐
	IsOriginal    bool      `gorm:"column:is_original;default:1;comment:是否原创" json:"is_original"`                 // 是否原创
	Description   string    `gorm:"column:description;comment:文章简介，最多200字" json:"description"`                    // 文章简介，最多200字
	Keywords      string    `gorm:"column:keywords;comment:文章关键字，优化搜索" json:"keywords"`                           // 文章关键字，优化搜索
	CreateTime    time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:添加时间" json:"create_time"` // 添加时间
}

// TableName LdNote's table name
func (*LdNote) TableName() string {
	return TableNameLdNote
}
