// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameRecipesComment = "recipes_comments"

// RecipesComment mapped from table <recipes_comments>
type RecipesComment struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CommentID       int64     `gorm:"column:comment_id" json:"comment_id"`
	BeCommentUserID int64     `gorm:"column:be_comment_user_id;comment:被评论人的雪花算法 id" json:"be_comment_user_id"` // 被评论人的雪花算法 id
	CommenterID     int64     `gorm:"column:commenter_id;comment:评论人的雪花算法 id" json:"commenter_id"`              // 评论人的雪花算法 id
	RecipeID        int64     `gorm:"column:recipe_id;comment:菜品 雪花算法 id" json:"recipe_id"`                     // 菜品 雪花算法 id
	ParentCommentID int64     `gorm:"column:parent_comment_id;comment:回复评论类型的id" json:"parent_comment_id"`      // 回复评论类型的id
	CommentText     string    `gorm:"column:comment_text;comment:回复的文字内容" json:"comment_text"`                  // 回复的文字内容
	CommentTime     time.Time `gorm:"column:comment_time;default:CURRENT_TIMESTAMP" json:"comment_time"`
	HasRead         int32     `gorm:"column:has_read;default:2;comment:是否已经阅读过,1,已经读过，2 未读过" json:"has_read"` // 是否已经阅读过,1,已经读过，2 未读过
}

// TableName RecipesComment's table name
func (*RecipesComment) TableName() string {
	return TableNameRecipesComment
}
