// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameRecipe = "recipes"

// Recipe mapped from table <recipes>
type Recipe struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`                       // 自增主键
	RecipeID    int64     `gorm:"column:recipe_id;comment:食谱ID（自增主键）" json:"recipe_id"`                                 // 食谱ID（自增主键）
	CategoryID  int64     `gorm:"column:category_id;not null;comment:菜谱分类ID（外键，关联recipe_category表）" json:"category_id"` // 菜谱分类ID（外键，关联recipe_category表）
	RecipeName  string    `gorm:"column:recipe_name;not null;comment:菜谱名称" json:"recipe_name"`                          // 菜谱名称
	Difficulty  string    `gorm:"column:difficulty;comment:难度级别" json:"difficulty"`                                     // 难度级别
	Ingredients string    `gorm:"column:ingredients;comment:食材列表（可以是JSON格式存储，方便处理多条食材信息）" json:"ingredients"`           // 食材列表（可以是JSON格式存储，方便处理多条食材信息）
	Directions  string    `gorm:"column:directions;not null;comment:制作步骤" json:"directions"`                            // 制作步骤
	Images      string    `gorm:"column:images;comment:菜谱图片URL" json:"images"`                                          // 菜谱图片URL
	AuthorID    int64     `gorm:"column:author_id;not null;comment:创建者用户ID（关联users表）" json:"author_id"`                 // 创建者用户ID（关联users表）
	Status      int32     `gorm:"column:status;not null;default:1;comment:状态[-1:删除;0:禁用;1启用]" json:"status"`            // 状态[-1:删除;0:禁用;1启用]
	CreateTime  time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:数据创建时间" json:"create_time"`       // 数据创建时间
	UpdateTime  time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:数据更新时间" json:"update_time"`       // 数据更新时间
	Cover       string    `gorm:"column:cover;comment:菜品封面" json:"cover"`                                               // 菜品封面
	IsDelete    int32     `gorm:"column:is_delete;default:1;comment:菜品是否删除 1 正常 2 删除" json:"is_delete"`                 // 菜品是否删除 1 正常 2 删除
}

// TableName Recipe's table name
func (*Recipe) TableName() string {
	return TableNameRecipe
}
