// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameRecipeCategory = "recipe_category"

// RecipeCategory mapped from table <recipe_category>
type RecipeCategory struct {
	ID                  int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键为自增的id" json:"id"` // 主键为自增的id
	CategoryID          int64     `gorm:"column:category_id;not null" json:"category_id"`
	CategoryName        string    `gorm:"column:category_name;not null" json:"category_name"`
	CategoryDescription string    `gorm:"column:category_description" json:"category_description"`
	ParentCategoryID    int64     `gorm:"column:parent_category_id" json:"parent_category_id"`
	Status              int32     `gorm:"column:status;not null;default:1;comment:状态[-1:删除;0:禁用;1启用]" json:"status"`      // 状态[-1:删除;0:禁用;1启用]
	CreateTime          time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:数据创建时间" json:"create_time"` // 数据创建时间
	UpdateTime          time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:数据更新时间" json:"update_time"` // 数据更新时间
}

// TableName RecipeCategory's table name
func (*RecipeCategory) TableName() string {
	return TableNameRecipeCategory
}
