// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameWechatUser = "wechat_users"

// WechatUser 用户表，记录系统中的所有用户信息
type WechatUser struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键为自增的id" json:"id"`             // 主键为自增的id
	Userid        int64     `gorm:"column:userid;not null;comment:用户ID" json:"userid"`                              // 用户ID
	Username      string    `gorm:"column:username;not null;comment:用户名" json:"username"`                           // 用户名
	Avatar        string    `gorm:"column:avatar;comment:用户头像" json:"avatar"`                                       // 用户头像
	Openid        string    `gorm:"column:openid;not null;comment:微信小程序 openid" json:"openid"`                      // 微信小程序 openid
	Sessionkey    string    `gorm:"column:sessionkey;not null;comment:小程序登录凭证" json:"sessionkey"`                   // 小程序登录凭证
	Userpoint     int32     `gorm:"column:userpoint;comment:用户积分" json:"userpoint"`                                 // 用户积分
	Userstatus    bool      `gorm:"column:userstatus;comment:用户状态" json:"userstatus"`                               // 用户状态
	CreateTime    time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:数据创建时间" json:"create_time"` // 数据创建时间
	UpdateTime    time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:数据更新时间" json:"update_time"` // 数据更新时间
	CanAddRecipes int32     `gorm:"column:can_add_recipes" json:"can_add_recipes"`
}

// TableName WechatUser's table name
func (*WechatUser) TableName() string {
	return TableNameWechatUser
}
