// Code generated by goctl. DO NOT EDIT.
package types

type AddNewNoteRequest struct {
	Title         string `json:"title"`
	ContentMd     string `json:"content_md"`
	CoverImage    string `json:"cover_image"`
	Top           bool   `json:"top"`
	TypeId        int64  `json:"type_id"`
	TagIds        string `json:"tag_ids"`
	IsOriginal    bool   `json:"is_original"`
	IsRecommended bool   `json:"is_recommended"`
	Description   string `json:"description"`
	Keywords      string `json:"keywords"`
}

type AddNewNoteResponse struct {
}

type AddCatRequest struct {
	Cat_name string `json:"catName"`
	Cat_desc string `json:"catDesc"`
}

type AddCatResponse struct {
	Id string `json:"id"`
}

type Request struct {
}

type Response struct {
	Version string
}
