// Code generated by goctl. DO NOT EDIT.
package types

type AddCatRequest struct {
	Cat_name string `json:"catName"`
	Cat_desc string `json:"catDesc"`
}

type AddCatResponse struct {
	Id string `json:"id"`
}

type Request struct {
}

type Response struct {
	Version string
}
